name: Build and Push

on:
  push:
    branches:
      - main

jobs:

  build:

    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Convert owner to lowercase
        run: echo "OWNER_LC=${OWNER,,}" >> $GITHUB_ENV
        env:
          OWNER: ${{ github.repository_owner }}

      - name: Login GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Image
        run: |
          docker build \
          -t ghcr.io/${{ env.OWNER_LC }}/delta-ws-bot:latest .

      - name: Push Image
        run: |
          docker push \
          ghcr.io/${{ env.OWNER_LC }}/delta-ws-bot:latest